### ISSUE TITLE
The full image isn't loading

### ISSUE THREAD

**Issue by LunaAshai** [fanfare/googleimagesrestored#37] opened 2020-02-21 05:11 UTC
The image isn't loading and this affects both the preview and 'View Image'

For 'View Image', it is linking to data:image/jpeg

Edit: It seems like this doesn't affect most of the images viewed through 'Related Images'

![bug](https://user-images.githubusercontent.com/8222603/75006072-5f713800-5425-11ea-8b22-b9a4ab501b29.png)

This happens on Chrome and Firefox

**Comment by fanfare** [comment] 2020-02-21 06:18
if you open up the devtools console, does it print out anything when you try to click on the thumbnails?

**Comment by joolsmtw** [comment] 2020-02-21 12:40
Can confirm all of the above - console just prints "there was an issue fetching the thumb", sometimes "bad response from server shut down", althought this seems to be unrelated to the thumbs no loading. The respective lines in main.js are 1723:21 and 1482:25.

Thumbs load _sometimes_, when you click the preload. When you open thumbs through the "related images" tab, they load a lot more often.

**Comment by LunaAshai** [comment] 2020-02-21 17:55
The console mainly prints out "there was an issue fetching the thumb" for me.

Also, it looks like if you scroll down far enough, the thumbnails there will actually load properly.

**Comment by fanfare** [comment] 2020-02-21 17:58
thanks this was helpful i'll try and look into it more. seems like maybe
more A/B testing which isnt easy to reproduce here locally unfortunately..
so annoying

**Comment by fanfare** [comment] 2020-02-21 20:20
fixed in 0.2.4 -- its very fragile not sure how long it will last sorry

**Closed by fanfare** 2020-02-21 20:20 UTC
