### ISSUE TITLE
weird bug when i searched images (maybe it was bug from using google sign-in)

### ISSUE THREAD

**Issue by MossyMosMos** [fanfare/googleimagesrestored#91] opened 2023-04-06 02:42 UTC
when i search images today, the weird bug was happened to me, it start with very few amount of images or even not shown to me (maybe it was bug from google sign-in) usually it should be started to show more than this.
<img width="960" alt="imagesearchbug" src="https://user-images.githubusercontent.com/126743138/230258943-4ad17cb2-4b7e-4d7f-85ac-451722fa6ea6.png">

<img width="960" alt="imagesearchbug2" src="https://user-images.githubusercontent.com/126743138/230259401-c00da3fe-3ca9-4504-8cd2-d818c74387be.png">

**Comment by fanfare** [comment] 2023-04-06 17:44
im unable to reproduce it locally here so it might just be A/B testing unfortunately ill keep an eye out though in case this starts to happen on my end

**Comment by MossyMosMos** [comment] 2023-04-06 22:17
i found out the bug was happened when i used google accounts sign-in, even if i'd tried removed an extension or anything out, the bug still happened the same. it seem works fine when i used google sign-out, maybe it was happened from my google sign-in bugs and it may not related to any extensions

**Comment by fanfare** [comment] 2023-04-07 00:05
ok, thanks for the update; closing for now

**Closed by fanfare** 2023-04-07 00:05 UTC
