### ISSUE TITLE
High Res Images Don't Load Passed Third Line (ish)

### ISSUE THREAD

**Issue by Sxderp** [fanfare/googleimagesrestored#48] opened 2020-04-09 01:00 UTC
When you perform a search the first three lines of images are loaded right away. Anything passed these lines are loaded async. If you click on an image from the first few lines, the ones loading synchronously, the high-res image will be loaded. If you click on an image further down the high-res image never loads. Though, if you click on a related image the related image's high-res will load (doesn't affect the original non-load).

**Comment by fanfare** [comment] 2020-04-10 00:29
hey-- i just tested this out and it seems like the situation is still fine on my end.. i cant reproduce what you are describing. so it looks like more A/B testing stuff i need to look out for, in case it starts to break globally. ill leave this open since it seems like a potential problem that will start to be widespread soon

**Comment by mikhoul** [comment] 2020-04-10 00:35
Here's what the Google Search image GUI is looking for me: 
![image](https://user-images.githubusercontent.com/5678673/78951802-5e619c00-7aa1-11ea-844c-cfe4aa5b288d.png)


Could you make q quick "plain" UserSript that would only show the image size all the time without hovering ?

Regards :octocat:

**Comment by fanfare** [comment] 2020-04-20 03:22
sorry for the delay, just pushed a fix in 0.2.9
https://github.com/fanfare/googleimagesrestored/releases/tag/0.2.9

**Comment by Sxderp** [comment] 2021-01-07 13:18
Looks like this issue (or very similar) has reappeared.

**Comment by fanfare** [comment] 2021-01-07 23:49
i see it too, ill see what i can do

**Comment by fanfare** [comment] 2021-01-08 00:28
attempted to fix this in `0.3.3` via https://github.com/fanfare/googleimagesrestored/releases/tag/0.3.3
if you want to try - otherwise the updates should be in the chrome/firefox extensions page after they are reviewed
if it still isn't working ill have to look closer but this patch worked for me

**Closed** 2021-01-09 20:32 UTC
