### ISSUE TITLE
GIR no longer functions properly on Firefox

### ISSUE THREAD

**Issue by RandyKing** [fanfare/googleimagesrestored#83] opened 2022-12-05 21:42 UTC
This code has worked beautifully ever since the Googlia screwed it up back in 2019.  However; now _SOME_ thumbnails will not open; instead, clicking on them simply refreshes the page.  It sort-of looks like a copy protection attempt, but I can't seem to find any common thread to when it does and when it does not work.  Also, disabling the add-on in Firefox, then refreshing the page and re-enabling it has it working sometimes.

**Comment by fanfare** [comment] 2022-12-06 02:05
do you happen to know which version you are using? i ended up having to make a new firefox account because I got locked out of my old account. the version on the old account was stuck at `0.4.5` (and is broken) but the newest version is `0.4.9` (and should be working ok) - have you tried that one? here's a link to it for firefox: [https://addons.mozilla.org/en-US/firefox/addon/google-images-restored-backup/](https://addons.mozilla.org/en-US/firefox/addon/google-images-restored-backup/) 
if you are already using that one i'll try and take a look, but on my end everything is still working OK so it might unfortunately be A/B testing.

**Comment by fanfare** [comment] 2022-12-09 08:44
there's a new release, version [`0.5.0`](https://github.com/fanfare/googleimagesrestored/releases/tag/0.5.0) which from my testing is working fine on my end. closing for now, will be on the lookout in case i can reproduce what you were describing locally.

**Closed by fanfare** 2022-12-09 08:44 UTC
